### ISSUE TITLE
Density prompt up to date + script experiments up-to-date + more stuff

### ISSUE THREAD

**Issue by antonlaukemper** [PGiagkoulas/dmas#41]
also change cluster distance to float

- remove the logic about n_agents to n_connection
and replace it with check on max connection

**Comment by PGiagkoulas** [comment]
Description for load_experiment added
Short addition to description for Connection_density
Checking for maximum number of connections
Cluster distance can be float
Number of agents can be changed and connections are adjusted accordingly. (maybe to-be-removed in general)

**Comment by PGiagkoulas** [comment]
Fixed minimum connection number (removed as discussed)
